---
version: '2.4'
#only add core CCD services here. Side services should be added to others.yaml

services:
  ccd-shared-database-v11:
    build: ../database-v11
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      DB_USERNAME:
      DB_PASSWORD:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5050:5432
    volumes:
      - ccd-docker-ccd-shared-database-data-v11:/var/lib/postgresql/data
    networks:
      - ccd-network

  ccd-user-profile-api:
    image: "${CCD_USER_PROFILE_API_USE_LOCAL-hmctspublic.azurecr.io/}ccd/user-profile-api:${CCD_USER_PROFILE_API_TAG:-latest}"
    environment:
      USER_PROFILE_DB_HOST: "${CCD_POSTGRES_11:-ccd-shared-database}"
      USER_PROFILE_DB_PORT: 5432
      USER_PROFILE_DB_USERNAME: "${DB_USERNAME}"
      USER_PROFILE_DB_PASSWORD: "${DB_PASSWORD}"
      USER_PROFILE_DB_USE_SSL: "${DB_USE_SSL}"
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      REFORM_SERVICE_NAME: ccd-user-profile-api
      REFORM_TEAM: ccd
      REFORM_ENVIRONMENT: local
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 4453:4453
    depends_on:
      - ${CCD_POSTGRES_11:-ccd-shared-database}
    networks:
      - ccd-network

  ccd-definition-store-api:
    image: "${CCD_DEFINITION_STORE_API_USE_LOCAL-hmctspublic.azurecr.io/}ccd/definition-store-api:${CCD_DEFINITION_STORE_API_TAG:-latest}"
    environment:
      DEFINITION_STORE_DB_HOST: "${CCD_POSTGRES_11:-ccd-shared-database}"
      DEFINITION_STORE_DB_PORT: 5432
      DEFINITION_STORE_DB_USERNAME: "${DB_USERNAME}"
      DEFINITION_STORE_DB_PASSWORD: "${DB_PASSWORD}"
      DEFINITION_STORE_DB_USE_SSL: "${DB_USE_SSL}"
      DEFINITION_STORE_IDAM_KEY: "${IDAM_KEY_CCD_DEFINITION_STORE}"
      DEFINITION_STORE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_gw,ccd_admin,aac_manage_case_assignment
      USER_PROFILE_HOST: http://ccd-user-profile-api:4453
      IDAM_USER_URL: "${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}"
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      REFORM_SERVICE_NAME: ccd-definition-store-api
      REFORM_TEAM: ccd
      REFORM_ENVIRONMENT: local
      APPINSIGHTS_INSTRUMENTATIONKEY: key
      ELASTIC_SEARCH_ENABLED: "${ES_ENABLED_DOCKER}"
      ELASTIC_SEARCH_HOST: "ccd-elasticsearch"
      ELASTIC_SEARCH_FAIL_ON_IMPORT: "true"
      # Uncomment this line to enable JVM debugging and uncomment the port mapping below
      # JAVA_TOOL_OPTIONS: '-XX:InitialRAMPercentage=30.0 -XX:MaxRAMPercentage=65.0 -XX:MinRAMPercentage=30.0 -XX:+UseConcMarkSweepGC -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'
    ports:
      - 4451:4451
      # Uncomment this and the JAVA_TOOL_OPTIONS flag for JVM debugging
      # - 5005:5005
    depends_on:
      # Uncomment this line to enable ccd test stub service
      rse-idam-simulator:
        condition: service_started
#      idam-api:
#        condition: service_started
      ccd-shared-database-v11:
        condition: service_started
      ccd-user-profile-api:
        condition: service_started
    networks:
      - ccd-network

  ccd-data-store-api:
    image: "${CCD_DATA_STORE_API_USE_LOCAL-hmctspublic.azurecr.io/}ccd/data-store-api:${CCD_DATA_STORE_API_TAG:-latest}"
    environment:
      CASE_DOCUMENT_AM_URL: http://ccd-case-document-am-api:4455
      DATA_STORE_DB_HOST: "${CCD_POSTGRES_11:-ccd-shared-database}"
      DATA_STORE_DB_PORT: 5432
      DATA_STORE_DB_USERNAME: "${DB_USERNAME}"
      DATA_STORE_DB_PASSWORD: "${DB_PASSWORD}"
      DATA_STORE_DB_USE_SSL: "${DB_USE_SSL}"
      DATA_STORE_IDAM_KEY: "${IDAM_KEY_CCD_DATA_STORE}"
      DATA_STORE_TOKEN_SECRET: iuasbcuasdcbasdgcasdgcuysachjsacyasdgjcgasdj
      DATA_STORE_S2S_AUTHORISED_SERVICES: ccd_gw,ccd_gateway,fpl_case_service,ccd_data,ccd_ps,aac_manage_case_assignment,
        xui_webapp,ccd_case_document_am_api,am_role_assignment_service,
        ethos_repl_docmosis_service,ecm_consumer,et_cos,et_msg_handler,et_sya_api,wa_workflow_api,
        wa_task_management_api,wa_task_monitor,wa_case_event_handler
      DEFINITION_STORE_HOST: http://ccd-definition-store-api:4451
      USER_PROFILE_HOST: http://ccd-user-profile-api:4453
      IDAM_USER_URL: "${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}" # For backward compatibility with older images
      IDAM_API_BASE_URL: "${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}"
      IDAM_OIDC_URL: "${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}"
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      IDAM_OAUTH2_DATA_STORE_CLIENT_SECRET: idam_data_store_client_secret
      REFORM_SERVICE_NAME: ccd-data-store-api
      REFORM_TEAM: ccd
      REFORM_ENVIRONMENT: local
      APPINSIGHTS_INSTRUMENTATIONKEY: key
      ELASTIC_SEARCH_ENABLED: "${ES_ENABLED_DOCKER}"
      ELASTIC_SEARCH_HOSTS: ccd-elasticsearch:9200
      ELASTIC_SEARCH_DATA_NODES_HOSTS: "http://ccd-elasticsearch:9200"
      CCD_DEFAULTPRINTURL: https://return-case-doc-ccd.nonprod.platform.hmcts.net/jurisdictions/:jid/case-types/:ctid/cases/:cid
      CCD_DOCUMENT_URL_PATTERN: "${CCD_DOCUMENT_URL_PATTERN}"
      ENABLE_ATTRIBUTE_BASED_ACCESS_CONTROL: "${ENABLE_ATTRIBUTE_BASED_ACCESS_CONTROL:-true}"
      ENABLE_PSEUDO_ROLE_ASSIGNMENTS_GENERATION: "${ENABLE_PSEUDO_ROLE_ASSIGNMENTS_GENERATION:-true}"
      ENABLE_PSEUDO_ACCESS_PROFILES_GENERATION: "${ENABLE_PSEUDO_ACCESS_PROFILES_GENERATION:-true}"
      ROLE_ASSIGNMENT_URL: "${ROLE_ASSIGNMENT_URL:-http://am-role-assignment-service:4096}"
      # Uncomment this line to enable JVM debugging and uncomment the port mapping below
      # JAVA_TOOL_OPTIONS: '-XX:InitialRAMPercentage=30.0 -XX:MaxRAMPercentage=65.0 -XX:MinRAMPercentage=30.0 -XX:+UseConcMarkSweepGC -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'
    ports:
      - 4452:4452
      # Uncomment this and the JAVA_TOOL_OPTIONS flag for JVM debugging
      # - 5005:5005
    depends_on:
      rse-idam-simulator:
        condition: service_started
#      idam-api:
#        condition: service_started
      ccd-shared-database-v11:
        condition: service_started
      ccd-user-profile-api:
        condition: service_started
      ccd-definition-store-api:
        condition: service_started
    networks:
      - ccd-network

  am-role-assignment-service:
    image: "${AM_ROLE_ASSIGNMENT_SERVICE_USE_LOCAL-hmctspublic.azurecr.io/}am/role-assignment-service:${AM_ROLE_ASSIGNMENT_SERVICE_TAG:-latest}"
    environment:
      ROLE_ASSIGNMENT_DB_HOST: "${CCD_POSTGRES_11:-ccd-shared-database}"
      ROLE_ASSIGNMENT_DB_NAME: role_assignment
      ROLE_ASSIGNMENT_DB_PORT: 5432
      ROLE_ASSIGNMENT_DB_USERNAME: "${DB_USERNAME}"
      ROLE_ASSIGNMENT_DB_PASSWORD: "${DB_PASSWORD}"
      ROLE_ASSIGNMENT_DB_OPTIONS:
      AM_ROLE_ASSIGNMENT_SERVICE_SECRET: "${IDAM_KEY_AM_ROLE_ASSIGNMENT}"
      LD_SDK_KEY:
      ROLE_ASSIGNMENT_IDAM_KEY:
      ROLE_ASSIGNMENT_TOKEN_SECRET:
      ROLE_ASSIGNMENT_S2S_AUTHORISED_SERVICES: ccd_gw,am_role_assignment_service,am_org_role_mapping_service,wa_task_management_api,xui_webapp,ccd_data
      IDAM_USER_URL: "${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}"
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      OPEN_ID_API_BASE_URI: "${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}/o"
      OIDC_ISSUER_URL: "${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}/openam/oauth2/hmcts"
      ROLE_ASSIGNMENT_IDAM_CLIENT_ID: am_role_assignment
      ROLE_ASSIGNMENT_IDAM_CLIENT_SECRET: am_role_assignment_secret
      ROLE_ASSIGNMENT_IDAM_ADMIN_USERID: role.assignment.admin@gmail.com
      ROLE_ASSIGNMENT_IDAM_ADMIN_PASSWORD: "${AM_ROLE_AADMINGMENT_ADMIN_PWD:-Pa55word11}"
      ROLE_ASSIGNMENT_IDAM_ADMIN_SCOPE: profile openid roles search-user
      CCD_DATA_STORE_URL: http://ccd-data-store-api:4452
      AZURE_APPLICATIONINSIGHTS_INSTRUMENTATIONKEY:
      REFORM_SERVICE_NAME: am-role-assignment-service
      REFORM_TEAM: am
      REFORM_ENVIRONMENT: local
      # Uncomment this line to enable JVM debugging and uncomment the port mapping below
      #  JAVA_TOOL_OPTIONS: -XX:InitialRAMPercentage=30.0 -XX:MaxRAMPercentage=65.0 -XX:MinRAMPercentage=30.0 -XX:+UseConcMarkSweepGC -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - 4096:4096
      # Uncomment this and the JAVA_TOOL_OPTIONS flag for JVM debugging
      # - 5005:5005
    depends_on:
      rse-idam-simulator:
        condition: service_started
#      idam-api:
#        condition: service_started
      ccd-shared-database-v11:
        condition: service_started
      ccd-data-store-api:
        condition: service_started
    networks:
      - ccd-network

  service-auth-provider-api:
    image: "hmctspublic.azurecr.io/rpe/service-auth-provider:latest"
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - 4502:8080
    environment:
      SERVER_PORT: 8080
      JWT_KEY: wThK0f0/lh3FlxFcL4xUWDMI5C1J9KyQBgXV4wseh1e5J1uYJIjvTvArHxQDrYoHJ23xFxjHkOnvNbR5dXRoxA==
      MICROSERVICEKEYS_AAC_MANAGE_CASE_ASSIGNMENT: "${BEFTA_S2S_CLIENT_SECRET_OF_AAC_MANAGE_CASE_ASSIGNMENT}"
      MICROSERVICEKEYS_CCD_DATA: "${IDAM_KEY_CCD_DATA_STORE}"
      MICROSERVICEKEYS_CCD_GW: "${IDAM_KEY_CCD_GATEWAY}"
      MICROSERVICEKEYS_CCD_DEFINITION: "${IDAM_KEY_CCD_DEFINITION_STORE}"
      MICROSERVICEKEYS_CCD_ADMIN: "${IDAM_KEY_CCD_ADMIN}"
      MICROSERVICEKEYS_CCD_PS: "${IDAM_KEY_CCD_PS}"
      MICROSERVICEKEYS_FPL_CASE_SERVICE: "${IDAM_KEY_FPL_CASE_SERVICE}"
      MICROSERVICEKEYS_XUI_WEBAPP: "${BEFTA_S2S_CLIENT_SECRET_OF_XUI_WEBAPP}"
      MICROSERVICEKEYS_PAYMENT_APP: "${BEFTA_S2S_CLIENT_SECRET_OF_PAYMENT_APP}"
      MICROSERVICEKEYS_CCD_CASE_DOCUMENT_AM_API : "${IDAM_KEY_CASE_DOCUMENT}"
      MICROSERVICEKEYS_BULK_SCAN_PROCESSOR: "${IDAM_KEY_BULK_SCAN_PROCESSOR}"
      MICROSERVICEKEYS_AM_ROLE_ASSIGNMENT_SERVICE: "${IDAM_KEY_AM_ROLE_ASSIGNMENT}"
      MICROSERVICEKEYS_ETHOS_REPL_DOCMOSIS_SERVICE: "${IDAM_KEY_ETHOS_REPL_DOCMOSIS_SERVICE}"
      MICROSERVICEKEYS_ECM_CONSUMER: "${IDAM_KEY_ECM_CONSUMER}"
      MICROSERVICEKEYS_ET_COS: "${IDAM_KEY_ET_COS}"
      MICROSERVICEKEYS_ET_SYA_API: "${IDAM_KEY_ET_SYA_API}"
      MICROSERVICEKEYS_ET_MSG_HANDLER: "${IDAM_KEY_ET_MSG_HANDLER}"
      MICROSERVICEKEYS_WA_WORKFLOW_API: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_WA_TASK_MANAGEMENT_API: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_WA_TASK_CONFIGURATION_API: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_WA_CASE_EVENT_HANDLER: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_WA_TASK_MONITOR: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_CAMUNDA_BPM: "AAAAAAAAAAAAAAAA"
      TESTING_SUPPORT_ENABLED: "true"
    networks:
      - ccd-network

  camunda-local-bpm:
    image: "hmctsprivate.azurecr.io/camunda/bpm:latest"
    environment:
      CAMUNDA_NEXUS_USER: "ministry_of_justice_uk"
      CAMUNDA_NEXUS_PASSWORD: "Bq?49xrwGENwLgC!"
      CAMUNDA_DB_HOST: "${CCD_POSTGRES_11:-ccd-shared-database}"
      CAMUNDA_DB_PORT: 5432
      CAMUNDA_DB_USER_NAME: "ccd"
      CAMUNDA_DB_PASSWORD: "ccd"
      camunda.bpm.database.schema-update: "true"
      CAMUNDA_API_AUTH_ENABLED: "false"
      S2S_URL: http://service-auth-provider-api
      camundaGroups.work-allocation.s2sServiceNames: wa_task_management_api,wa_workflow_api,wa_case_event_handler,wa_camunda_pipeline_upload
      WA_AUTO_CONFIGURE_TASKS_ENABLED: "True"
      TASK_MANAGEMENT_API_URL: "http://localhost:8087"
      TZ: Europe/London
    ports:
      - 8999:8999
    depends_on:
      ccd-shared-database-v11:
        condition: service_started
    networks:
      - ccd-network

  ccd-message-publisher:
    image: "hmctspublic.azurecr.io/ccd/message-publisher:latest"
    container_name: message-publisher
    environment:
      DATA_STORE_DB_HOST: "${CCD_POSTGRES_11:-ccd-shared-database}"
      DATA_STORE_DB_PORT: 5432
      DATA_STORE_DB_USERNAME: "${DB_USERNAME}"
      DATA_STORE_DB_PASSWORD: "${DB_PASSWORD}"
      SERVICE_BUS_CONNECTION_STRING: "${AZURE_SERVICE_BUS_CONNECTION_STRING}"
      CCD_CASE_EVENTS_DESTINATION: "${AZURE_SERVICE_BUS_TOPIC_NAME}"
    ports:
      - 4456:4456
    networks:
      - ccd-network

  wa-workflow-api:
    image: "hmctspublic.azurecr.io/wa/workflow-api:latest"
    container_name: workflow-api
    environment:
      CAMUNDA_URL: http://camunda-bpm:8999/engine-rest
      S2S_URL: http://service-auth-provider-api:8080
      S2S_SECRET_WORKFLOW_API: "AAAAAAAAAAAAAAAA"
      POSTGRES_HOST: "${CCD_POSTGRES_11:-ccd-shared-database}"
      POSTGRES_PORT: 5432
      POSTGRES_NAME: wa_workflow_api
      POSTGRES_USERNAME: "${DB_USERNAME:-postgres}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-postgres}"
      WA_S2S_AUTHORIZED_SERVICES: wa_workflow_api,wa_case_event_handler,camunda-bpm,xui_webapp
      LAUNCH_DARKLY_SDK_KEY: "${LAUNCH_DARKLY_SDK_KEY}"
    ports:
      - 8099:8099
    depends_on:
      - ccd-shared-database-v11
      - service-auth-provider-api
      - camunda-local-bpm
    links:
      - ccd-shared-database-v11
      - service-auth-provider-api
      - camunda-local-bpm
    networks:
      - ccd-network

  wa-task-management-api:
    image: "hmctspublic.azurecr.io/wa/task-management-api:latest"
    container_name: wa-task-management-api
    environment:
      CAMUNDA_URL: http://camunda-bpm:8999/engine-rest
      S2S_URL: http://service-auth-provider-api:8080
      IDAM_URL: http://rse-idam-simulator:5000
      CCD_URL: http://ccd-data-store-api:4452
      POSTGRES_HOST: ccd-shared-database-v11
      OPEN_ID_IDAM_URL: http://rse-idam-simulator:5000
      ROLE_ASSIGNMENT_URL: http://am-role-assignment-service:4096
      POSTGRES_PORT: 5432
      POSTGRES_NAME: cft_task_db
      ALLOWED_JURISDICTIONS: wa,ia,sscs,civil
      ALLOWED_CASE_TYPES: asylum,wacasetype,sscs,civil
      WA_S2S_AUTHORIZED_SERVICES: ccd,ccd_data,ccd_gw,ccd_ps,iac,wa_task_management_api,xui_webapp,wa_task_monitor,camunda_bpm,wa_workflow_api
      LAUNCH_DARKLY_SDK_KEY: "${LAUNCH_DARKLY_SDK_KEY}"
      WA_SYSTEM_USERNAME: "${WA_SYSTEM_USERNAME}"
      WA_SYSTEM_PASSWORD: "${WA_SYSTEM_PASSWORD}"
    ports:
      - 8087:8087
    depends_on:
      - ccd-shared-database-v11
      - service-auth-provider-api
      - camunda-local-bpm
    networks:
      - ccd-network

  case-event-handler:
    image: "hmctspublic.azurecr.io/wa/case-event-handler:latest"
    container_name: case-event-handler
    environment:
      POSTGRES_HOST: ccd-shared-database-v11
      AZURE_SERVICE_BUS_CONNECTION_STRING: "${AZURE_SERVICE_BUS_CONNECTION_STRING}"
      AZURE_SERVICE_BUS_TOPIC_NAME: "${AZURE_SERVICE_BUS_TOPIC_NAME}"
      AZURE_SERVICE_BUS_SUBSCRIPTION_NAME: "${AZURE_SERVICE_BUS_SUBSCRIPTION_NAME}"
      AZURE_SERVICE_BUS_CCD_CASE_EVENTS_SUBSCRIPTION_NAME: "${AZURE_SERVICE_BUS_CCD_CASE_EVENTS_SUBSCRIPTION_NAME}"
      POSTGRES_CONNECTION_OPTIONS: "?stringtype=unspecified&gssEncMode=disable"
      APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=00000000-0000-0000-0000-000000000000"
      ENVIRONMENT: "local"
      S2S_URL: http://service-auth-provider-api:8080
      WA_WORKFLOW_API_URL: http://wa-workflow-api:8099
      OPEN_ID_IDAM_URL: http://rse-idam-simulator:5000
      IDAM_URL: http://rse-idam-simulator:5000
      ROLE_ASSIGNMENT_URL: http://am-role-assignment-service:4096
      CAMUNDA_URL: http://camunda-bpm:8999/engine-rest
      CCD_URL: http://ccd-data-store-api:4452
      AZURE_SERVICE_BUS_FEATURE_TOGGLE: "true"
      AZURE_SERVICE_BUS_DLQ_FEATURE_TOGGLE: "true"
      AZURE_SERVICE_BUS_CONCURRENT_SESSIONS: 2
      MESSAGE_PROCESSING_POLL_INTERVAL_MILLISECONDS: 2000
      MESSAGE_PROCESSING_THREAD_POOL_SIZE: 5
      MESSAGE_READINESS_POLL_INTERVAL_MILLISECONDS: 500
      MESSAGE_READINESS_THREAD_POOL_SIZE: 2
      LAUNCH_DARKLY_SDK_KEY: "${LAUNCH_DARKLY_SDK_KEY}"
    ports:
      - 8088:8088
    depends_on:
      - ccd-shared-database-v11
      - service-auth-provider-api
      - camunda-local-bpm
      - am-role-assignment-service
      - wa-workflow-api
    networks:
      - ccd-network

  wa-task-monitor:
    image: "hmctspublic.azurecr.io/wa/task-monitor:latest"
    container_name: wa-task-monitor
    environment:
      S2S_URL: http://service-auth-provider-api:8080
      WA_WORKFLOW_API_URL: http://wa-workflow-api:8099
      OPEN_ID_IDAM_URL: http://rse-idam-simulator:5000
      IDAM_URL: http://rse-idam-simulator:5000
      ROLE_ASSIGNMENT_URL: http://am-role-assignment-service:4096
      CAMUNDA_URL: http://camunda-bpm:8999/engine-rest
      CCD_URL: http://ccd-data-store-api:4452
      TASK_MANAGEMENT_SERVICE_URL: http://wa-task-management-api:8087
      CASE_EVENT_HANDLER_SERVICE_URL: http://wa-case-event-handler:8088
      CCD_SEARCH_URL: http://ccd-elasticsearch:9200
      CONFIGURATION_CAMUNDA_MAX_RESULTS: 100
      CONFIGURATION_TIME_LIMIT_FLAG: "true"
      CONFIGURATION_TIME_LIMIT: 1440
      INITIATION_CAMUNDA_MAX_RESULTS: 100
      INITIATION_TIME_LIMIT_FLAG: "true"
      INITIATION_TIME_LIMIT: 120
      TERMINATION_CAMUNDA_MAX_RESULTS: 100
      TERMINATION_TIME_LIMIT_FLAG: "true"
      TERMINATION_TIME_LIMIT: 120
      PENDING_TERMINATION_CAMUNDA_MAX_RESULTS: 1
      WA_SYSTEM_USERNAME: "${WA_SYSTEM_USERNAME}"
      WA_SYSTEM_PASSWORD: "${WA_SYSTEM_PASSWORD}"
    ports:
      - 8077:8077
    depends_on:
      - service-auth-provider-api
      - case-event-handler
      - wa-task-management-api
      - ccd-elasticsearch
      - am-role-assignment-service
    networks:
      - ccd-network

volumes:
  ccd-docker-ccd-shared-database-data-v11:
  #wiremock:

networks:
  ccd-network:
    external: true
